##### Numpy Array

In [1]:
import numpy as np
np.array([1,2,3,'Hello','Arjun'])

array(['1', '2', '3', 'Hello', 'Arjun'], dtype='<U11')

In [2]:
type(np.array([1,2,3,'Hello','Arjun']))

numpy.ndarray

In [3]:
#upcasting
k=np.array([1,2,3,4]) #it's a one dimentional array
type(k)

numpy.ndarray

In [4]:
#For two dimentional array
np.array([[1,2,3,4,'Hello']]) 

array([['1', '2', '3', '4', 'Hello']], dtype='<U11')

In [5]:
#n dimentional array
np.array([1,2,3,'hello'],ndmin=5) #here ndmin=5 is a 5 dimentional array

array([[[[['1', '2', '3', 'hello']]]]], dtype='<U11')

In [6]:
#For complex datatypes
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#if Data-type consisting of more than one element:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [8]:
type(x[1][0])

numpy.int16

In [9]:
#Creating matrix an array from sub classes
np.matrix(np.array([[1,2],[3,4],[5,6]]))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
np.mat(np.array([[1,2],[3,4],[5,6]]))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
np.mat('1,2,3;4,5,6')

matrix([[1, 2, 3],
        [4, 5, 6]])

##### numpy.asarray

asarray : The input will be returned uncopied iff it's a compatible ndarray ( copy=False ).     
asanyarray : The input will be returned uncopied iff it's a compatible ndarray or subclass like matrix ( copy=False , subok=True )

In [12]:
#convert the input to an array
#converting the list into an array
a=[1,2,3]
print(type(a))
a

<class 'list'>


[1, 2, 3]

In [13]:
type(a)

list

In [14]:
a=np.array([1,2,3])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3])

In [15]:
type(a)

numpy.ndarray

In [16]:
#If dtype is set, array is copied only if dtype does not match:
a=np.array([1,2,3,5.6],dtype=np.float)
a

array([1. , 2. , 3. , 5.6])

In [164]:
a=np.array([1,2,3,5.6],dtype=np.float32)
a

array([1. , 2. , 3. , 5.6], dtype=float32)

In [165]:
a=np.matrix([[1,2,3],[4,5,6]])
np.asarray(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
a

matrix([[1, 2, 3],
        [4, 5, 6]])

The major difference is that np.array will make a copy of the original object and not edit it unless copy is not set to false. Meaning that the original object remains unchanged. np.asarray would reflect the changes in the original array like object itself.

In [19]:
np.asarray(a) is a # Here a value memory location is different, so that we get False value

False

In [20]:
np.asanyarray(a) is a # Here a value memory location is same so that we get False value

True

In [21]:
a=[1,2,3]
np.asanyarray(a)

array([1, 2, 3])

In [22]:
a=np.matmul([1,2,3],[4,5,6])
a

32

In [23]:
#Create an array x, with a reference y and a copy z:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [24]:
y=x
y

array([1, 2, 3])

In [25]:
z=np.copy(x)
z

array([1, 2, 3])

In [26]:
id(x[1])

2397895022128

In [27]:
id(y[1])

2397895022176

In [28]:
id(z[1])

2397895022200

In [29]:
i=100
id(i)

1912764576

In [30]:
j=i
id(j)

1912764576

In [31]:
k=np.copy(i)
id(k)

2397913284000

##### numpy.fromfunction

In [32]:
#Construct an array by executing a function over each coordinate.
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j ,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [34]:
#Create a new 1-dimensional array from an iterable object.
iterable = (x*x for x in range(10))
iterable    #here output creates general expression value

<generator object <genexpr> at 0x0000022E4EC47410>

In [35]:
iterable = list(x*x for x in range(10))
iterable

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [36]:
np.fromiter(iterable,float)   #fromiter works values are printed iteration wise like iter method

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [37]:
# How to create create a record array from a (float) list of arrays
#A new 1-D array initialized from text data in a string
a = np.fromstring('233 44 433',sep = ' ')
a

array([233.,  44., 433.])

In [38]:
a=np.fromstring('1,2,3,4',dtype=int,sep=',')
a

array([1, 2, 3, 4])

In [39]:
x1=np.array([1,2,3,4])  #in np.arrays all the varible elements sign be same
x2=np.array(['a','dd','xyz','12'])
#x3=x1+x2
#x3

In [40]:
l1=[1,2,3,4]  # But in list we can ddd with any sign
l2=['a','dd','xyz','12']
l3=l1+l2
l3

[1, 2, 3, 4, 'a', 'dd', 'xyz', '12']

In [41]:
x1=np.array([1,2,3,4])  #in np.arrays all the varible elements sign must be same
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([3.4,5,3,6])
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 3.4), (2, 'dd', 2. , 5. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 6. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [42]:
type(r)

numpy.recarray

In [43]:
r[2][1]

'xyz'

###### data types

In [44]:
my_list=[1,2,3]
import numpy as np
arr=np.array(my_list)
print("Type/Class of this object: ",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object:  <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [45]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [46]:
my_mat=[[1.1,2,3],[4,5.6,4],[6.7,4,5.4,8]]
mat=np.array(my_mat)
print(list(mat))
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

[[1.1, 2, 3], [4, 5.6, 4], [6.7, 4, 5.4, 8]]
Data type of the modified matrix: object


Even tuples can be converted to ndarrays...


In [47]:
type(mat)

numpy.ndarray

In [48]:
b=np.array([(1.5,2,3),(4,5.5,6)])
print(type(b))
print("\nMatrix made from tuples, not lists\n---------------------------------------")
print(b)

<class 'numpy.ndarray'>

Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.5 6. ]]


###### arange and linspace

In [49]:
print('A Series of numbers: ',type(np.arange(5,10)))
np.arange(5,16,2.5)

A Series of numbers:  <class 'numpy.ndarray'>


array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [50]:
range(1,10,2)   #the diff b/t range and arange is 
                #in range we are not able to get float values
                #in arange we are able to get float values 

range(1, 10, 2)

In [51]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [52]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [53]:
list(range(50,-1,5))

[]

In [54]:
print("Numbers spaced apart by 2:",np.arange(-1,50,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [-1  4  9 14 19 24 29 34 39 44 49]


In [55]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [56]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


##### linespace - linearly spaced numbers between the given values

In [57]:
print("21 linearly spaced numbers between 1 and 5\n----------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
----------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [58]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

###### Matrix Creation

In [59]:
print('Vector of Zeros\n-----------------')
print(np.zeros(5))  #one dmentional vector matrix

Vector of Zeros
-----------------
[0. 0. 0. 0. 0.]


In [60]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,3)))  # two dimentional vector matrix
                        # notice here (3,4) are tuples

Matrix of zeroes
--------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:
##### print("Vector of ones\n---------------------")
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
print("Matrix of ones\n---------------------")
print(np.ones((3,2,5))) # Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [64]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


#####  eye - Return a 2-D array with ones on the diagonal and zeros elsewhere. 

In [65]:
#eye works like a identity matrix
mat1= np.eye(4)
print("Identity matrix of dimension", mat1.shape)
mat1

Identity matrix of dimension (4, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.arange(3)

array([0, 1, 2])

In [67]:
np.arange(3.5)

array([0., 1., 2., 3.])

In [68]:
np.arange(3,8,1.6)

array([3. , 4.6, 6.2, 7.8])

In [69]:
np.linspace(2.0,3.0,8)

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        ])

In [70]:
np.linspace(2.0,3.0,num=7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [71]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [72]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [73]:
np.linspace(2,4,num=30,retstep=True)

(array([2.        , 2.06896552, 2.13793103, 2.20689655, 2.27586207,
        2.34482759, 2.4137931 , 2.48275862, 2.55172414, 2.62068966,
        2.68965517, 2.75862069, 2.82758621, 2.89655172, 2.96551724,
        3.03448276, 3.10344828, 3.17241379, 3.24137931, 3.31034483,
        3.37931034, 3.44827586, 3.51724138, 3.5862069 , 3.65517241,
        3.72413793, 3.79310345, 3.86206897, 3.93103448, 4.        ]),
 0.06896551724137931)

In [74]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [75]:
np.logspace(2.0,3.0,num=5,base=10)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [76]:
np.logspace(2.0,3.0,num=5,base=2)

array([4.        , 4.75682846, 5.65685425, 6.72717132, 8.        ])

In [77]:
#Extract a diagonal or construct a diagonal array.
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.diag(x)

array([ 0,  5, 10, 15])

In [79]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [80]:
np.diag(x,k=1) #Diagonal elements

array([ 1,  6, 11])

In [81]:
np.diag(x,k=-1) 

array([ 4,  9, 14])

In [82]:
#### Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2],[3,4],[5,6,7,65,44],[33]])

array([[list([1, 2]), 0, 0, 0],
       [0, list([3, 4]), 0, 0],
       [0, 0, list([5, 6, 7, 65, 44]), 0],
       [0, 0, 0, list([33])]], dtype=object)

In [83]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [84]:
np.diagflat([1,2], -1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [85]:
#return a Lower triangle of an array.
np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [86]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [88]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],-2)

array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

In [89]:
#return Upper triangle of an array.
np.triu(np.tril([[1,2,3],[4,5,6],[7,8,9]],1))

array([[1, 2, 0],
       [0, 5, 6],
       [0, 0, 9]])

In [90]:
np.triu(np.tril([[1,2,3],[4,5,6],[7,8,9]],2))

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

######  Random number generation

In [91]:
print("Random number generation (from Uniform distribution)")
np.random.rand(2,3) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)


array([[0.38402235, 0.70026358, 0.82158836],
       [0.58926206, 0.51607475, 0.70723526]])

In [92]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
np.random.randn(2,3)

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal


array([[ 0.14788764,  0.83544404, -1.11744702],
       [-2.08342134, -0.02706226, -1.29577649]])

In [93]:
#np.random.rand means generated random numbers
#np.random.randn means generated random numbers along with means is zeroasnd std is 1

In [94]:
np.random.randint(1,10)

7

In [95]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn

Random integer vector: 8


In [96]:
print ("\nRandom integer matrix")
np.random.randint(1,100,(4,4))


Random integer matrix


array([[92, 99, 26, 12],
       [57, 36, 37, 97],
       [70, 67, 87,  8],
       [99, 89, 32, 70]])

In [97]:
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw


Random integer matrix
[[27  5 74 35]
 [72 26 98 59]
 [ 7  5 26 20]
 [41 32 70  8]]

20 samples drawn from a dice throw: [2 1 5 6 6 2 6 3 5 2 3 1 4 5 5 5 6 6 2 1]


#### Reshaping

In [98]:
from numpy.random import randint as ri

In [99]:
a=ri(1,100,30)
b=a.reshape(2,3,5)
c=a.reshape(6,-10)
c

array([[ 9,  7, 24, 96, 24],
       [59, 23, 48, 49, 26],
       [61, 69, 37, 48, 64],
       [62, 53, 32, 53, 28],
       [42, 44, 31, 95, 37],
       [36, 56, 98, 81, 35]])

In [100]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [101]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [ 9  7 24 96 24 59 23 48 49 26 61 69 37 48 64 62 53 32 53 28 42 44 31 95
 37 36 56 98 81 35] 
 --------------------

b looks like
 -------------------- 
 [[[ 9  7 24 96 24]
  [59 23 48 49 26]
  [61 69 37 48 64]]

 [[62 53 32 53 28]
  [42 44 31 95 37]
  [36 56 98 81 35]]] 
 --------------------

c looks like
 -------------------- 
 [[ 9  7 24 96 24]
 [59 23 48 49 26]
 [61 69 37 48 64]
 [62 53 32 53 28]
 [42 44 31 95 37]
 [36 56 98 81 35]] 
 --------------------


In [102]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [39 29 13 34  5 16  7 84 10 14]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5  7 10 13 14 16 29 34 39 84]


In [103]:
#Sorting the matrix
M=ri(1,100,25).reshape(5,5)
M

array([[36, 17, 62, 28,  6],
       [29, 49, 99,  2, 87],
       [87, 65, 96, 48, 76],
       [63, 97,  5, 86, 91],
       [38, 99, 15, 13,  7]])

In [104]:
np.sort(M,axis=1)

array([[ 6, 17, 28, 36, 62],
       [ 2, 29, 49, 87, 99],
       [48, 65, 76, 87, 96],
       [ 5, 63, 86, 91, 97],
       [ 7, 13, 15, 38, 99]])

In [105]:
print("Max of a:", M.max())
print("Max of b:", b.max())

Max of a: 99
Max of b: 98


In [106]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [2 2 2 1 1]
Max of b location: 27
Max of c location: 27


#### Indexing and slicing

In [107]:
arr=np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [108]:
print("Element at 7th index is:", arr[7])

Element at 7th index is: 7


In [109]:
print("Elements from 3rd to 5th index are:", arr[2:5])

Elements from 3rd to 5th index are: [2 3 4]


In [110]:
print("Elements from 2nd to 10th index with interval of 2 are:", arr[2:11:2])

Elements from 2nd to 10th index with interval of 2 are: [ 2  4  6  8 10]


In [111]:
print("Elements up to 4th index are:",arr[:4])

Elements up to 4th index are: [0 1 2 3]


In [112]:
print("Elements from last backwards are:",arr[::-1])

Elements from last backwards are: [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [113]:
print("Elements from last backwards are:", arr[-5:7:-1])

Elements from last backwards are: [10  9  8]


In [114]:
print("Elements from last backwards are:", arr[-2:2:-2])

Elements from last backwards are: [13 11  9  7  5  3]


In [115]:
print("3 Elements from last backwards are:",arr[-1:11:-1])

3 Elements from last backwards are: [14 13 12]


In [116]:
arr= np.arange(0,21,2)
print("New array", arr)

New array [ 0  2  4  6  8 10 12 14 16 18 20]


In [117]:
print("Elements at 2nd, 4th, and 9th index are:" ,arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [118]:
import numpy as np
mat=np.array(ri(10,100,25)).reshape(5,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:,5:5]

Matrix of random 2-digit numbers
--------------------------------
 [[15 64 15 89 77]
 [45 96 85 72 80]
 [59 96 17 86 35]
 [11 15 28 75 46]
 [37 71 59 72 79]]


array([], shape=(4, 0), dtype=int32)

In [119]:
mat[0:3,[1,3]]

array([[64, 89],
       [96, 72],
       [96, 86]])

In [120]:
print(mat)
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:",mat[1][2] )

[[15 64 15 89 77]
 [45 96 85 72 80]
 [59 96 17 86 35]
 [11 15 28 75 46]
 [37 71 59 72 79]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 85


In [121]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1,3 and column index 3:", mat[[1,3],[2]])


Single bracket with comma indexing
----------------------------------
Element in row index 1,3 and column index 3: [85 28]


In [122]:
mat[[1,3],[2]]

array([85, 28])

In [123]:
print("\nRow or column extract\n----------------------")
print("Entire row at index 2:",mat[2])
print("Entire column at index 3:", mat[:,3])


Row or column extract
----------------------
Entire row at index 2: [59 96 17 86 35]
Entire column at index 3: [89 72 86 75 72]


In [124]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[72 80]
 [86 35]]


In [125]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n",mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[64 89]
 [96 72]]


##### # Subseting

In [126]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n----------------\n",mat)

Matrix of random 2-digit numbers
----------------
 [[48 62 25 52 13]
 [61 91 24 96 47]
 [76 92 90 49 93]]


In [127]:
mat>50

array([[False,  True, False,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False,  True]])

In [128]:
print ("Elements greater than 50\n",mat[mat>50])

Elements greater than 50
 [62 52 61 91 96 76 92 90 93]


###### Slicing

In [129]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [130]:
mat_slice=mat[:2,:2]
mat_slice

array([[11, 12],
       [21, 22]])

In [131]:
print ("\nChange the sliced matrix")
mat_slice[0,0] =1000
mat_slice


Change the sliced matrix


array([[1000,   12],
       [  21,   22]])

In [132]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [133]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat= np.array([[11,12,13],[21,22,23],[31,32,33]])
print('Original matrix')
print(mat)


Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [134]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


Sliced matrix
[[11 12]
 [21 22]]


In [135]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


Change the sliced matrix
[[1000   12]
 [  21   22]]


In [136]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


##### Universal Functions

In [137]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------------------\n",mat2)


1st Matrix of random single-digit numbers
------------------------
 [[1 7 3]
 [9 8 1]
 [9 2 2]]

2nd Matrix of random single-digit numbers
------------------------
 [[3 1 2]
 [6 9 4]
 [1 3 7]]


In [138]:
mat1*mat2

array([[ 3,  7,  6],
       [54, 72,  4],
       [ 9,  6, 14]])

In [139]:
print("\nAddition\n------------------\n", mat1+mat2)


Addition
------------------
 [[ 4  8  5]
 [15 17  5]
 [10  5  9]]


In [140]:
print("\nMultiplication\n------------------\n", mat1@mat2)


Multiplication
------------------
 [[48 73 51]
 [76 84 57]
 [41 33 40]]


In [141]:
print("\nDivision\n------------------\n", mat1/0)


Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [142]:
print("\nLineaer combination: 3*A - 2*B\n----------------\n", 3*mat1-2*mat2)


Lineaer combination: 3*A - 2*B
----------------
 [[-3 19  5]
 [15  6 -5]
 [25  0 -8]]


In [143]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


Addition of a scalar (100)
-------------------------
 [[101 107 103]
 [109 108 101]
 [109 102 102]]


In [144]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)


Exponentiation, matrix cubed here
----------------------------------------
 [[  1 343  27]
 [729 512   1]
 [729   8   8]]


In [145]:
print("\nExponentiation, sq-root using pow function\n-------------------------------\n",pow(mat1,3))


Exponentiation, sq-root using pow function
-------------------------------
 [[  1 343  27]
 [729 512   1]
 [729   8   8]]


#### Broadcasting

The Broadcasting Rule    
In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

In [146]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [147]:
start = np.zeros((4,4))
start

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
start = start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [149]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1,0,2,5])
print(add_rows)

[1 0 2 5]


In [150]:
y=start + add_rows # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [151]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [152]:
# add to each column of 'start' using broadcasting
Z=start + add_cols
print(Z)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [153]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])
add_scalar

array([100])

In [154]:
print(start+add_scalar)

[[200. 200. 200. 200.]
 [200. 200. 200. 200.]
 [200. 200. 200. 200.]
 [200. 200. 200. 200.]]


In [155]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]]


###### Array math

In [156]:
mat1= np.array(ri(1,10,9)).reshape(3,3)
mat2= np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[8 1 7]
 [1 7 7]
 [2 1 3]]

2nd Matrix of random single-digit numbers
------------
 [[9 2 2]
 [8 7 7]
 [8 9 8]]


In [157]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[2.82842712 1.         2.64575131]
 [1.         2.64575131 2.64575131]
 [1.41421356 1.         1.73205081]]


In [158]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.98095799e+03 2.71828183e+00 1.09663316e+03]
 [2.71828183e+00 1.09663316e+03 1.09663316e+03]
 [7.38905610e+00 2.71828183e+00 2.00855369e+01]]


In [159]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.90308999 0.         0.84509804]
 [0.         0.84509804 0.84509804]
 [0.30103    0.         0.47712125]]


In [160]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))


Modulo reminder using np
 -------------------------------------------------- 
 [[8 1 1]
 [1 0 0]
 [2 1 3]]


In [161]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))


Modulo reminder using np
 -------------------------------------------------- 
 [[8 1 1]
 [1 0 0]
 [2 1 3]]


In [162]:
mat1%mat2

array([[8, 1, 1],
       [1, 0, 0],
       [2, 1, 3]], dtype=int32)